### ISSUE TITLE
TypeScript shortcut

### ISSUE THREAD

**Issue by agleymelo** [Rocketseat/rocketseat-vscode-reactjs-snippets#13]
Some people should program in TS (Typescript) using the snippets of reactjs, I think it would be a good idea to add a snippets for TS (Typescript) for example **rfcts** the ts would be the meaning for TS (Typescript)

**Comment by jpedroschmitz** [comment]
Hey @agleymelo, I think it's a great idea to support TypeScript snippets. I have been using it a lot and would love to have some shortcuts to create my components and pages. What do you think @diego3g?
